{% set name = "eo-learn-visualization" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1df73f3b5ec93a6f25fdf25e737c482622a9e84c7a485243ca25b883d92fab0e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - python-graphviz
    - jinja2
    - matplotlib-base
    - pydot
    - pygments
    - python >=3.5
    - geoviews
    - hvplot
    - pyepsg
    - xarray
test:
  imports:
    - eolearn
    - eolearn.visualization
  requires:
    - python-graphviz
    - eo-learn-core
about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of visualization utilities
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.visualization.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
